language: go
go:
- 1.13
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_a65247dffca0_key -iv $encrypted_a65247dffca0_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
addons:
  ssh_known_hosts: 46.101.138.224

before_deploy:
  - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa