sudo: required

services:
  - docker

#before_install:
  #- docker build -t akezhanob1/customer-service .

#script:
 # - docker run -d --restart=always -p 50055:50055 akezhanob1/customer-service

after_success:
  - docker build -t akezhanob1/customer-service .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akezhanob1/customer-service
