version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "50055:50055"
  client:
    build:
      context: .
      dockerfile: ./api/graphql/Dockerfile
    links:
      - server
    ports:
      - "8081:8081"